### ISSUE TITLE
Workflow failure - processing Summary ServicePrincipalsAppRoleAssignments

### ISSUE THREAD

**Issue by cjtous1** [JulianHayward/AzADServicePrincipalInsights#27]
Here is the error message I see in the github actions logs:
```
processing Summary ServicePrincipalsAppRoleAssignments
AzADServicePrincipalInsights.ps1: /home/runner/work/_temp/ab3aa0e7-ff1c-4b58-8b6c-194328e0298d.ps1:3
Line |
   3 |  . .\$($env:ScriptDir)\$($env:ScriptFile) -ScriptPath ${env:ScriptDir} …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Value cannot be null. (Parameter 'key')
Error: Error: The process '/usr/bin/pwsh' failed with exit code 1
```

This error started happening with v1_20240209_1, I believe...

**Comment by DarxonHU** [comment]
I have the very same issue since updating to v1_20240209_1

`processing Summary ServicePrincipalsAppRoleAssignments
##[error]Value cannot be null. (Parameter 'key')
##[error]PowerShell exited with code '1'.
Added TLS 1.2 in session.
Disconnect-AzAccount -Scope Process -ErrorAction Stop
Clear-AzContext -Scope Process -ErrorAction Stop
Finishing: Run AzADServicePrincipalInsights v1`

**Comment by JulianHayward** [comment]
@cjtous1 @DarxonHU thanks for reporting. Can you try the branch [fix_issue27](https://github.com/JulianHayward/AzADServicePrincipalInsights/tree/fix_issue27)
